version: '2'
services:
    nginx:
        build: docker/nginx
        ports:
            - "8050:80"
        links:
            - php
        volumes:
            - .:/var/www/ctf
    php:
        build: docker/php
        ports:
            - "9000"
        links:
            - mysql
        environment:
            DB_HOST: mysql
        volumes:
            - .:/var/www/ctf
    mysql:
        image: mysql
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: hellyeah
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
